//https://docs.google.com/spreadsheets/d/1MEsiJZK8CGi8K4aIHltIp1FS1pQaWLCbYp9KQqsUq-Q/edit?gid=1936754909#gid=1936754909
export const fgaChartTypeMapping = [
  {
    cardId: 50934,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up"],
  },
  {
    cardId: 51099,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up"],
  },
  {
    cardId: 51098,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up"],
  },
  {
    cardId: 51104,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up"],
  },
  {
    cardId: 50988,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up", "login"],
  },
  {
    cardId: 51103,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 51066,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 51080,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 51101,
    plan: "standard",
    category: "web3",
    type: "nft_address",
  },
  {
    cardId: 51100,
    plan: "standard",
    category: "web3",
    type: "nft_address",
  },
  {
    cardId: 51078,
    plan: "standard",
    category: "web3",
    type: "nft_address",
  },
  {
    cardId: 51017,
    plan: "standard",
    category: "web3",
    type: "nft_address",
  },
  {
    cardId: 51076,
    plan: "standard",
    category: "web3",
    type: "nft_address",
  },
  {
    cardId: 51079,
    plan: "standard",
    category: "web3",
    type: "nft_address",
  },
  {
    cardId: 51012,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 51014,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 51015,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 51012,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 51018,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 51016,
    plan: "standard",
    category: "web3",
    type: "nft_address",
  },
  {
    cardId: 51017,
    plan: "standard",
    category: "web3",
    type: "nft_address",
  },
  {
    cardId: 50935,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up"],
  },
  {
    cardId: 51019,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up"],
  },
  {
    cardId: 51020,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["linked_wallet"],
  },
  {
    cardId: 50944,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["linked_wallet"],
  },
  {
    cardId: 50945,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["linked_wallet"],
  },
  {
    cardId: 50946,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["login"],
  },
  {
    cardId: 50947,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["login"],
  },
  {
    cardId: 50949,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["login"],
  },
  {
    cardId: 50948,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["login"],
  },
  {
    cardId: 50941,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["login"],
  },
  {
    cardId: 51026,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 51027,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 51028,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 51029,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },




  {
    cardId: 45138,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 45139,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 45140,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 45137,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 50937,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up", "login"],
  },
  {
    cardId: 50938,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up", "login"],
  },
  {
    cardId: 50943,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up", "login"],
  },
  {
    cardId: 50942,
    plan: "standard",
    category: "web2",
    type: "tracked_events",
    subType: ["sign_up", "login"],
  },
  {
    cardId: 45393,
    plan: "advanced",
    category: "web2",
    type: "playgame_events",
  },
  {
    cardId: 45394,
    plan: "advanced",
    category: "web2",
    type: "playgame_events",
  },
  {
    cardId: 45395,
    plan: "advanced",
    category: "web2",
    type: "playgame_events",
  },
  {
    cardId: 45396,
    plan: "advanced",
    category: "web2",
    type: "playgame_events",
  },
  {
    cardId: 45245,
    plan: "advanced",
    category: "web2",
    type: "playgame_events",
  },
  {
    cardId: 43605,
    plan: "advanced",
    category: "web2",
    type: "playgame_events",
  },
  {
    cardId: 51022,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 51021,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 51023,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 51024,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 51025,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 51038,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 51036,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 47792,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },




  {
    cardId: 48879,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 48882,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 48880,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 48881,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 48883,
    plan: "standard",
    category: "web3",
    type: "protocol_slug",
  },
  {
    cardId: 47772,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 47779,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 47773,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 47774,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 47771,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 50466,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 47791,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 48049,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 48050,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 48045,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 47792,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 50401,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 50402,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 50403,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 50405,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 47789,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {
    cardId: 47790,
    plan: "standard",
    category: "web3",
    type: "token_address",
  },
  {"cardId": 46972, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46973, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46977, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46974, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46975, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46976, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 49019, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 49022, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 49021, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 49020, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46978, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46979, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46980, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46981, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46982, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46984, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 46983, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 50380, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 50381, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 50382, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 50383, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 50384, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 43333, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 43330, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 43331, plan: "standard","category": "web3", "type": "nft_address"},
  {"cardId": 48578, plan: "advanced","category": "web3", "type": "token_address"},
  {"cardId": 48575, plan: "advanced","category": "web3", "type": "token_address"},
  {"cardId": 48576, plan: "advanced","category": "web3", "type": "token_address"},
  {"cardId": 43420, plan: "advanced","category": "web3", "type": "nft_address"},
  {"cardId": 46998, plan: "advanced","category": "web3", "type": "nft_address"},
  {"cardId": 46999, plan: "advanced","category": "web3", "type": "nft_address"},
  {"cardId": 47000, plan: "advanced","category": "web3", "type": "nft_address"},
  {"cardId": 44987, plan: "advanced","category": "web3", "type": "nft_address"},
  {"cardId": 47001, plan: "advanced","category": "web3", "type": "nft_address"},
  {"cardId": 43398, plan: "advanced","category": "web3", "type": "nft_address"},
  {"cardId": 47002, plan: "advanced","category": "web3", "type": "nft_address"},
];
