name: 'Pull Request Notifier'

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: Netail/webhook-notifier@v1
      with:
        discord-url: ${{ secrets.DISCORD_URL }}
        slack-url: ${{ secrets.SLACK_URL }}
        color: 'info'
        title: 'A new pull request has been made: '
        text: ${{ github.event.pull_request.html_url }}
